services:
  - type: web
    name: hostel-meal-menu-backend
    runtime: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_VERSION
        value: 22.13.0
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: VERCEL
        value: "false"
